# Generated by Django 5.2.5 on 2025-08-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('procesador', models.CharField(max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes_computadoras')),
            ],
        ),
    ]
