# Generated by Django 5.2.5 on 2025-08-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadora',
            name='procesador',
        ),
    ]
