# Generated by Django 5.2.5 on 2025-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_computadora_procesador'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='precio',
            field=models.IntegerField(default=0, help_text='Precio en dólares'),
            preserve_default=False,
        ),
    ]
